### ISSUE TITLE
Error during make install

### ISSUE THREAD

**Issue by ghost** [Bowuigi/RSHW#4]
For some reason, I get this error when running `sudo make install`:

```
clang -Os -lreadline rshw.c -o rshw
In file included from rshw.c:1:
In file included from /usr/include/readline/readline.h:36:
/usr/include/readline/rltypedefs.h:71:36: error: unknown type name 'FILE'
typedef int rl_getc_func_t PARAMS((FILE *));
                                   ^
In file included from rshw.c:1:
/usr/include/readline/readline.h:448:28: error: unknown type name 'FILE'
extern int rl_getc PARAMS((FILE *));
                           ^
/usr/include/readline/readline.h:578:8: error: unknown type name 'FILE'
extern FILE *rl_instream;
       ^
/usr/include/readline/readline.h:579:8: error: unknown type name 'FILE'
extern FILE *rl_outstream;
       ^
/usr/include/readline/readline.h:937:3: error: unknown type name 'FILE'
  FILE *inf;
  ^
/usr/include/readline/readline.h:938:3: error: unknown type name 'FILE'
  FILE *outf;
  ^
6 errors generated.
make: *** [Makefile:13: build] Error 1
```

Maybe I don't have the correct libraries installed? I am on Arch Linux.

**Comment by Bowuigi** [comment]
Do you have the latest libreadline installed? Looks like it doesn't include <stdio.h> which is weird.

**Comment by Bowuigi** [comment]
Relevant GNU readline archwiki page: [GNU Readline - ArchWiki](https://wiki.archlinux.org/title/Readline)

**Comment by ghost** [comment]
I have readline 8.1.001-1 and clang 12.0.0-1 installed.

**Comment by Bowuigi** [comment]
Seems like it is recent enough, try adding `#include <stdio.h>` at the top of rshw.c and run the command again

**Comment by ghost** [comment]
That didn't work for me unfortunately

**Comment by ghost** [comment]
Never mind, it did end up working when I put it at the very top of the file. I will send in a PR to fix this.

**Comment by Bowuigi** [comment]
That is really weird, looks like your libreadline broke. Sorry

**Comment by Bowuigi** [comment]
Oh good
